-- liquibase formatted sql

-- changeset demaz:1
create table if not exists notification
(
    id                  bigint    generated by default as identity primary key,
    chat_id             bigint    not null,
    notification_text   text      not null,
    date_time           timestamp not null
);

create table if not exists pet
(
    id                  bigint    generated by default as identity primary key,
    pet_name            text      not null
);

create table if not exists connection
(
    id                  bigint    generated by default as identity primary key,
    pet_id              bigint    not null,
    chat_id             bigint    not null,
    date_time           timestamp not null
);

-- changeset demaz:2
create table if not exists shelter
(
    id                  bigint generated by default as identity primary key,
    name                text    not null,
    address             text    not null,
    info                text,
    map                 bytea
);

-- changeset demaz:3
create table if not exists volunteer
(
    id                  bigint generated by default as identity primary key,
    name                text    not null,
    chat_id             text    not null,
    phone_number        text    not null
);

-- changeset demaz:4
ALTER TABLE pet
    ADD age INTEGER not null,
    ADD photo BYTEA,
    ADD kind_of_animal TEXT not null,
    ADD animal_breed TEXT not null,
    ADD shelter_id BIGINT not null,
    ADD owner_id BIGINT;

-- changeset filippova-t:1
create table if not exists customer
(
    id                  bigint generated by default as identity primary key,
    name                text    not null,
    chat_id             text    not null,
    phone_number        text    not null
);

-- changeset demaz:5
create table if not exists report
(
    id                  bigint generated by default as identity primary key,
    chat_id             bigint  not null,
    text_report         text,
    date_report         timestamp not null,
    file_path           text,
    file_size           bigint,
    media_type          text,
    photo               bytea,
    pet_id              bigint  not null
);